### ISSUE TITLE
/Library/Extensions/AntiRTDPI.kext failed to load

### ISSUE THREAD

**Issue by vkryzh** [dzhidzhoev/AntiRTDPI#1]
I've got the next error. Integrity protection disabled. What can be a reason?
/Library/Extensions/AntiRTDPI.kext failed to load - (libkern/kext) dependency resolution failure; check the system/kernel logs for errors or try kextutil(8).

**Comment by diversys** [comment]
Have you tried to disable SPI? http://osxdaily.com/2015/10/05/disable-rootless-system-integrity-protection-mac-os-x/

**Comment by dzhidzhoev** [comment]
Try to rebuild your kext with dependencies. Building kexts is two-stage process: firstly you just build it using Cmd+B in Xcode, after that you have to check dependencies of kext using kextlibs and rebuild kext with these dependencies.
To fix your problem try to call `kextlibs -xml /Library/Extensions/AntiRTDPI.kext`. Copy the output. Then open project's Info.plist in text editor and paste the output before the latest </dict> tag. If there was another `<key>OSBundleLibraries</key><dict>...</dict>` section in Info.plist file, remove it. Rebuild your kext and try to use it.
